### ISSUE TITLE
get filenames for io.Reader/io.Writer

### ISSUE THREAD

**Issue by terinjokes** [bobziuchkovski/writ#6]
Is it possible to get the filenames for io.Reader and io.Writer options? I like the automatic handling of them, but still prefer to sometimes get to the filenames (for error messages and the like)

**Comment by bobziuchkovski** [comment]
Hi @terinjokes, you can use a type assertion.  When decoding to io.Reader, io.ReadCloser, io.Writer, and io.WriteCloser, the decoded field value will always be *os.File (or nil).  I'm happy to document that as well to make it "official".  That's an implementation detail you're welcome to rely upon.  Below is an example to show you how this works.  Alternatively, you can implement your own OptionDecoder for the file fields in question.  Some might consider that cleaner, but either approach will work.

Type assertion approach:

``` go
package main

import (
    "fmt"
    "github.com/bobziuchkovski/writ"
    "io"
    "os"
)

type Config struct {
    Input  io.Reader      `option:"i" description:"Input file" placeholder:"FILE" default:"-"`
    Output io.WriteCloser `option:"o" descripiton:"Output file" placeholder:"FILE" default:"-"`
}

func main() {
    cfg := &Config{}
    cmd := writ.New("dingus", cfg)
    _, _, err := cmd.Decode(os.Args[1:])
    if err != nil {
        cmd.ExitHelp(err)
    }
    in, out := cfg.Input.(*os.File), cfg.Output.(*os.File)
    fmt.Printf("dingus called with input file %q and output file %q\n", in.Name(), out.Name())
}
```

**Comment by bobziuchkovski** [comment]
Oh, and that example is relying on the default value of `-`, which signifies stdin/stdout per standard unix convention.  If you don't want to rely upon stdin/stdout as defaults, you'd want to drop the `default:"-"` from the struct tags and be more careful with the type assertion, too, checking first for nil, or using the two-value form of type assertions such as `if in, ok := cfg.Input.(*os.File); ok { <something with in> }`

**Comment by terinjokes** [comment]
@bobziuchkovski I was handling "-" specially when i was using `flag`, so I'm very happy you're now handling it for me. :smile: 

Thank you for the example. I tried to match to `os.File` before opening my question, so I'm glad to see I was thinking down the right path.

**Comment by bobziuchkovski** [comment]
No problem, glad I could help!
