### ISSUE TITLE
Support Embedded Structs for Commands

### ISSUE THREAD

**Issue by elithrar** [bobziuchkovski/writ#7]
This allows you to have a common set of options/flags across sub-commands - e.g.

``` go
type Common struct {
    FileName string
    Headers string
    ...
}

type Fetch struct {
    Common
    From string
}

type Restore struct {
    Common
    To []string
}
```

The structs here are simple, but should illustrate the use-case. The embedded struct does not seem to be parsed.

**Comment by bobziuchkovski** [comment]
@elithrar Sorry for the slow reply.  I was caught up between taxes and work.  I'll take a look over the next few days.  I definitely like any idea that DRYs up option parsing.  😄
